config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "index#index_action"

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index_action
    @tasks = Task.all
  end

  def show_action
    @task = Task.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render :new, status: :unprocessable_entity
    end

  end

  private
    def task_params
      params.require(:task).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/index_action.html.erb
<h1>HOME</h1>

<ul>
  <li>
    <%= link_to "Task List", tasks_path %>
  </li>
</ul>

app/views/index/show_action.html.erb
<h1>タスクの詳細</h1>

<ul>
  <li>title: <%= @task.title %></li>
  <li>isCompleted: <%= @task.is_completed %></li>
  <li>createdAt: <%= @task.created_at %></li>
</ul>

<%= link_to "HOME", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Task list</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task %>
    </li>
  <% end %>
</ul>

<%= link_to "HOME", root_path %>
<%= link_to "Create Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @task.errors.full_messages_for(:title).each do |message| %>
      <div style="color: red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h1>タスクの詳細</h1>

<ul>
  <li>title: <%= @task.title %></li>
  <li>isCompleted: <%= @task.is_completed %></li>
  <li>createdAt: <%= @task.created_at %></li>
</ul>

<%= link_to "HOME", root_path %>
<%= link_to "Task List", tasks_path %>